Repository ytdl-org/youtube-dl, pull requests merged in 2018-11, with the labels that each got.

#17199 [extractor/common] Ensure response handle is not prematurely closed before it can be read if it matches expected_status (resolves #17195)
  test/helper.py
  test/test_InfoExtractor.py
  test/test_downloader_http.py
  test/test_http.py
  youtube_dl/extractor/common.py
Labels: linux

#18044 [atv.at] fix initial video extraction
  youtube_dl/extractor/atvat.py
Labels: pending-fixes

#17767 [vk] handle an error message for video that is not available in your region.
  youtube_dl/extractor/vk.py
Labels: pending-fixes

#18228 [nzz] Extract Kaltura embeds from nzz.ch
  youtube_dl/extractor/nzz.py
Labels: pending-fixes

#18217 fix lynda.com signin
  youtube_dl/extractor/lynda.py
Labels: account-needed
