Repository ytdl-org/youtube-dl, pull requests merged in 2019-09, with the labels that each got.

#22246 Add support for Nickelodeonjunior.fr
  youtube_dl/extractor/nick.py
Labels: pending-fixes

#22268 [youtube] Add invidious tor instances
  youtube_dl/extractor/youtube.py
Labels: do-not-merge, pending-fixes

#22148 [jwplatfom] do not match video URLs(#20596)
  youtube_dl/extractor/jwplatform.py
Labels: invalid
