Repository ytdl-org/youtube-dl, pull requests merged in 2019-07, with the labels that each got.

#21565 [vevo] Add support for embed.vevo.com URLs
  youtube_dl/extractor/vevo.py
Labels: pending-fixes

#21607 Fix twitch downloading by tweaking VOD url
  youtube_dl/extractor/twitch.py
Labels: cant-reproduce

#21421 [yandexmusic] extract tracks from all volumes of an album (closes #21420)
  youtube_dl/extractor/yandexmusic.py
Labels: pending-fixes

#21780 [gfycat] Add ru/ to regex
  youtube_dl/extractor/gfycat.py
Labels: pending-fixes

#21775 [einthusan] adding .com tld
  youtube_dl/extractor/einthusan.py
Labels: pending-fixes

#21678 [CtsNews] Fix YouTube embed video url regex and test cases
  youtube_dl/extractor/ctsnews.py
Labels: pending-fixes

#21265 [YahooJapanNews] Add extractor.
  youtube_dl/extractor/extractors.py
  youtube_dl/extractor/yahoo.py
Labels: pending-fixes

#21901 Fix typos across youtube-dl repository
  youtube_dl/downloader/dash.py
  youtube_dl/downloader/ism.py
  youtube_dl/extractor/leeco.py
  youtube_dl/extractor/rtlnl.py
  youtube_dl/extractor/soundcloud.py
Labels: do-not-merge, pending-fixes

#21909 [dlive] extend VALID_URL regex to support VID with hyphens
  youtube_dl/extractor/dlive.py
Labels: pending-fixes

#21881 [mgtv] Add format_note.
  youtube_dl/extractor/mgtv.py
Labels: pending-fixes

#21915 Clarify batch file ERROR: message
  youtube_dl/__init__.py
Labels: pending-fixes
